---
title: "1. Getting started"
author: "1.1 What can we forecast?"
date: "OTexts.org/fpp3/"
classoption: aspectratio=169
titlepage: fpp3title.png
titlecolor: fpp3red
toc: false
output:
  binb::monash:
    colortheme: monashwhite
    fig_width: 7.5
    fig_height: 3.5
    keep_tex: no
    includes:
      in_header: fpp3header.tex
---

## Forecasts that aren't forecasts

\fullheight{hopecasts2}

## What can we forecast?

\only<1>{\fullheight{AusBOM}}
\only<2>{\placefig{0}{1.35}{height=10.8cm, width=20cm}{nasdaq-stock-market}}
\only<3>{\placefig{0}{1.35}{height=10.2cm, width=20cm}{Forex2}}
\only<4>{\placefig{0}{1.35}{height=12.2cm, width=20cm, trim=0 0 0 100, clip=true}{ts22015}}
\only<5>{\placefig{0}{1.35}{height=10.2cm, width=20cm}{comet}}
\only<6>{\placefig{0}{1.35}{height=11.2cm, width=20cm}{pills}}
\only<7>{\placefig{0}{1.35}{height=9.2cm, width=20cm}{elecwires}
\begin{textblock}{12}(0.2,8.8)\tiny\textcolor{gray}{\texttt{Varistor60, CC BY-SA 4.0, https://commons.wikimedia.org/w/index.php?curid=59368531}}
\end{textblock}}
\only<8>{\placefig{0}{1.35}{height=9.2cm, width=20cm}{covid}}
\only<9>{\placefig{0}{1.35}{height=10.2cm, width=20cm}{12apostles}}

## Which is easiest to forecast?

 * daily electricity demand in 3 days time
 * time of sunrise this day next year
 * Google stock price tomorrow
 * Google stock price in 6 months time
 * maximum temperature tomorrow
 * exchange rate of \$US/AUS next week
 * total sales of drugs in Australian pharmacies next month
 * timing of next Halley's comet appearance

\pause\begin{alertblock}{}\Large
\centerline{\textbf{pollev.com/robjhyndman}}
\end{alertblock}

\vspace*{10cm}

## Which is easiest to forecast?

 1. time of sunrise this day next year
 2. timing of next Halley's comet appearance
 3. maximum temperature tomorrow
 4. daily electricity demand in 3 days time
 5. total sales of drugs in Australian pharmacies next month
 6. Google stock price tomorrow
 7. exchange rate of \$US/AUS next week
 8. Google stock price in 6 months time

\only<2>{\begin{block}{}\begin{itemize}\tightlist
 \item how do we measure ``easiest''?
 \item what makes something easy/difficult to forecast?
 \end{itemize}\end{block}}

\vspace*{10cm}

## Forecastability factors

Something is easier to forecast if:

 1. we have a good understanding of the factors that contribute to it
 2. there is lots of data available;
 3. the future is somewhat similar to the past
 4. the forecasts cannot affect the thing we are trying to forecast.
